Vagrant.configure("2") do |config|
  config.vm.define "nfs-server" do |m|
      m.vm.box = "ubuntu/xenial64"
      m.vm.hostname = "nfs-server"
      m.vm.provision "shell", path: "nfs-server.sh"
      m.vm.network "private_network", ip: "192.168.33.10"
      m.vm.provider :virtualbox do |vb|
        vb.customize [ 'modifyvm', :id, '--memory', '512' ]
        vb.customize [ 'modifyvm', :id, '--name', 'nfs-server' ]
      end
  end
  config.vm.define "nfs-client-01" do |m|
      m.vm.box = "ubuntu/xenial64"
      m.vm.hostname = "nfs-client-01"
      m.vm.provision "shell", path: "nfs-client.sh"
      m.vm.network "private_network", ip: "192.168.33.11" 
      m.vm.provider :virtualbox do |vb| 
        vb.customize [ 'modifyvm', :id, '--memory', '512' ]
        vb.customize [ 'modifyvm', :id, '--name', 'nfs-client-01' ]
      end
  end
end
